Models/ErrorViewModel.cs
namespace hotelbook.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/HotelBooking.cs
namespace hotelbook.Models
{
    public class HotelBooking
    {
        public int Id { get; set; }
        public string GuestName { get; set; }
        public DateTime DateStart { get; set; }
        public DateTime DateEnd { get; set; }
    }
}

Controllers/HomeController.cs
using hotelbook.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace hotelbook.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/HotelBookController.cs
using hotelbook.Models;
using Microsoft.AspNetCore.Mvc;

namespace hotelbook.Controllers
{
    public class HotelBookController : Controller
    {
        private static List<HotelBooking> hotelBooked = new List<HotelBooking>();
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult HotelBookingDetails() {
                     
            return View(hotelBooked);
        }

        public IActionResult Register()
        {
            return View();
        }

        public IActionResult SubmitForm(HotelBooking hotelBooking)
        {
            hotelBooked.Add(hotelBooking);
            return RedirectToAction(nameof(HotelBookingDetails));
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/HotelBook/HotelBookingDetails.cshtml
@model List<hotelbook.Models.HotelBooking>

<h1>Hotel Book Details</h1>
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <ul>
                @foreach(var items in Model)
                {
                    <li>Guest ID : @items.Id</li>
                    <li>Guest Name : @items.GuestName</li>
                    <li>Guest Date Check In : @items.DateStart</li>
                    <li>Guest Date Check Out : @items.DateEnd</li>
                }
            </ul>
        </div>
    </div>
</div>

Views/HotelBook/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="d-flex justify-content-center mb-4">
    <h1>Welcome to Tarmizi Hotel</h1>
</div>

<hr/>

<div class="d-flex justify-content-center mt-3 mb-3">
    <p>You need to Book  24 hours prior check in!!</p>
</div>

<div class="d-flex justify-content-center mb-4">
    <p>Thank You!!</p>
</div>

Views/HotelBook/Register.cshtml
@model HotelBooking

<h1 class="d-flex justify-content-center">Guest Registration Detail</h1>
<hr/>
<div class="row">
    <div class="container d-flex justify-content-center"> 
        <div class="col-6">
            <div class="card">
                <div class="card-header text-center">
                    <h5>Book Your Room Here</h5>
                </div>
                <div class="card-body">
                    <form asp-controller="HotelBook" asp-action="SubmitForm" method="post">
                        <div class="mb-3">
                           <label class="form-label">ID</label>
                           <input asp-for="Id" type="number" class="form-control"/>
                        </div>
                        <div class="mb-3">
                           <label class="form-label">Enter Your Name</label>
                           <input asp-for="GuestName" type="text" class="form-control"/>
                        </div>
                        <div class="mb-3">
                            <label class="form-label">From Date</label>
                           <input asp-for="DateStart" type="datetime-local" class="form-control"/>
                        </div>
                        <div class="mb-3">
                            <label class="form-label">To Date</label>
                           <input asp-for="DateEnd" type="datetime-local" class="form-control"/>
                        </div>
                        <div>
                            <button class="btn btn-outline-primary" type="submit">Submit</button>
                        </div>
                    </form>
                </div>
                <div class="card-footer mt-2 mb-1">

                </div>
            </div>
        
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - hotelbook</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/hotelbook.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="HotelBook" asp-action="Index">Hotel Book App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HotelBook" asp-action="Index">Welcome Page</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HotelBook" asp-action="HotelBookingDetails">Guest List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HotelBook" asp-action="Register">Register</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - hotelbook - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>